GET http://127.0.0.1:28080/test_post_user?username=xxx&password=ooo
Accept: application/json

###
GET http://127.0.0.1:28080/test_get_user?type=1&username=aaa&password=ooo
Accept: application/json

###
GET http://127.0.0.1:28080/test_get_user?type=2&username=bbb&password=ooo
Accept: application/json

###
GET http://127.0.0.1:28080/test_get_user?type=3&username=ccc&password=ooo
Accept: application/json

###
GET http://127.0.0.1:28080/hello?name=world

###
