GET http://127.0.0.1:8888/actuator/gateway/routefilters
Accept: application/json

###
GET http://127.0.0.1:8888/actuator/gateway/globalfilters
Accept: application/json

###
GET http://127.0.0.1:8888/oschina

###
GET http://127.0.0.1:8888/baidu

### 测试 AuthGatewayFilterFactory
GET http://127.0.0.1:8888/baidu
access-token: yunai

###
GET http://127.0.0.1:8888/user-service/user/get?id=1
Accept: application/json

###
