GET http://127.0.0.1:28080/actuator/health
Accept: application/json

###
GET http://127.0.0.1:28080/actuator/nacosdiscovery
Accept: application/json

###
GET http://127.0.0.1:28080/hello?name=yudaoyuanma
Accept: application/json

###
