spring:
  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
          # 路由的编号
        - id: baidu
          # 路由到的目标地址
          uri: https://www.baidu.com
          # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
          predicates:
            - Path=/baidu
          # 过滤器，对请求进行拦截，实现自定义的功能，对应 FilterDefinition 数组
          filters:
            - StripPrefix=1
        - id: oschina
          uri: https://www.oschina.net
          predicates:
            - Path=/oschina
          filters:
            - StripPrefix=1
#