spring:
  main:
    #
    allow-circular-references: true
  application:
    name: sentinel-demo-provider

  cloud:
    # Sentinel 配置项，对应 SentinelProperties 配置属性类
    sentinel:
      # 是否开启。默认为 true 开启
      enabled: true
      # 是否饥饿加载。默认为 false 关闭
      eager: true
      transport:
        # Sentinel 控制台地址
        dashboard: 127.0.0.1:7070
      filter:
        # 拦截请求的地址。默认为 /*
        url-patterns: /**
#
