management:
  endpoints:
    web:
      exposure:
        # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
        include: '*'
  endpoint:
    # Health 端点配置项，对应 HealthProperties 配置类
    health:
      # 是否开启。默认为 true 开启。
      enabled: true
      # 何时显示完整的健康信息。默认为 NEVER 都不展示。可选 WHEN_AUTHORIZED 当经过授权的用户；可选 ALWAYS 总是展示。
      show-details: ALWAYS

spring:
  main:
    #
    allow-circular-references: true
  application:
    name: sentinel-demo-provider

  cloud:
    # Sentinel 配置项，对应 SentinelProperties 配置属性类
    sentinel:
      # 是否开启。默认为 true 开启
      enabled: true
      # 是否饥饿加载。默认为 false 关闭
      eager: true
      transport:
        # Sentinel 控制台地址
        dashboard: 127.0.0.1:7070
      filter:
        # 拦截请求的地址。默认为 /*
        url-patterns: /**
      # Sentinel 规则的数据源，是一个 Map 类型。key 为数据源名，可自定义；value 为数据源的具体配置
      datasource:
        ds1:
          # 对应 DataSourcePropertiesConfiguration 类
          nacos:
            # Nacos 服务器地址
            server-addr: 127.0.0.1:8848
            # Nacos 命名空间
            namespace:
            # Nacos 分组
            group-id: DEFAULT_GROUP
            # Nacos 配置集编号
            data-id: ${spring.application.name}-flow-rule
            # 数据格式
            data-type: json
            # 规则类型
            rule-type: FLOW
#
